# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
#permalink: pretty
permalink: /blog/:title/

# Setup
title: Rohith Mukku
tagline: 'Developer'
description: 'A computer science enthusiast seeking expertise and greater knowledge in his areas of interest.<br>Made using <a href="https://jekyllthemes.io/theme/hyde" target="_blank">Hyde Jekyll Theme</a>.'
url: http://rohithmukku.github.io
baseurl: 

author:
  name: 'Rohith Mukku'
  url: https://rohithmukku.github.io

paginate: 5

kramdown:
  parse_block_html: true

github:
  repo: https://github.com/rohithmukku

plugins:
  - jekyll-paginate
  - jekyll-gist

collections:
  tags:
    output: true
    permalink: tags/:path/
